(function(){
 const Graphite=window.Graphite=window.Graphite||{}; const SOURCE_VERSION=1; let running=false;
 const nativeAvailable=()=>Boolean(Graphite.native?.available&&Graphite.repositories?.isAvailable?.());
 function runId(){return crypto?.randomUUID?crypto.randomUUID():`migration-${Date.now()}-${Math.random().toString(16).slice(2)}`;}
 function validate(s){if(!s||typeof s!=="object")throw new Error("IndexedDB state is missing or invalid.");if(!Array.isArray(s.workspaces)||!s.workspaces.length)throw new Error("At least one workspace is required.");const ws=new Set(s.workspaces.map(w=>String(w.id)));if(ws.size!==s.workspaces.length)throw new Error("Duplicate workspace IDs detected.");const check=(a,n)=>{if(!Array.isArray(a))throw new Error(`${n} must be an array.`);const ids=new Set();a.forEach(x=>{if(!x||x.id==null||String(x.id).trim()==="")throw new Error(`${n} contains an item without an ID.`);const id=String(x.id);if(ids.has(id))throw new Error(`Duplicate ${n} ID: ${id}`);ids.add(id);if(x.workspaceId&&!ws.has(String(x.workspaceId)))throw new Error(`${n} item ${id} references a missing workspace.`);});};check(s.notes,"notes");check(s.flashcards,"flashcards");check(s.sessionLog,"sessions");["todo","progress","done"].forEach(c=>check(s.kanban?.[c]||[],`tasks:${c}`));return s;}
 async function backup(s){return Graphite.services.backup.create({format:"graphite-indexeddb-backup",formatVersion:1,source:{database:Graphite.persistence.DB_NAME,version:Graphite.persistence.DB_VERSION},createdAt:new Date().toISOString(),state:s});}
 async function status(){return nativeAvailable()?Graphite.native.invoke("migration_status"):({state:"unavailable",sourceOfTruth:"indexeddb"});}
 async function rollbackToCompatibilitySnapshot(){if(!nativeAvailable())throw new Error("SQLite migration recovery requires the native Tauri runtime.");const snapshot=validate(await Graphite.persistence.load());const report=await Graphite.dualWrite.syncNow(snapshot);if(!report?.verified)throw new Error("SQLite recovery verification did not pass.");Graphite.dualWrite.setAuthoritative(true);Graphite.events?.emit('storage:recovered',{sourceOfTruth:'sqlite',from:'indexeddb'});return report;}
 async function run(options={}){if(running)throw new Error("A Graphite migration is already running.");if(!nativeAvailable())throw new Error("SQLite migration requires the native Tauri runtime.");running=true;const id=runId();let begun=false;try{const snapshot=validate(await Graphite.persistence.load());Graphite.events?.emit("migration:progress",{stage:"backup",progress:0});const b=await backup(snapshot);Graphite.events?.emit("migration:progress",{stage:"backup",progress:1,backup:b});const prev=await status();if(prev.state==="completed"&&!options.force)return{status:prev,skipped:true};await Graphite.native.invoke("migration_begin",{input:{runId:id,sourceVersion:SOURCE_VERSION,backupPath:b.path}});begun=true;Graphite.events?.emit("migration:progress",{stage:"import",progress:0});const payload=Graphite.dualWrite?.payload?Graphite.dualWrite.payload(snapshot):snapshot;const report=await Graphite.native.invoke("migration_import_and_verify",{payload});Graphite.events?.emit("migration:progress",{stage:"verify",progress:1,report});if(!report?.verified)throw new Error("SQLite migration verification did not pass.");const done=await Graphite.native.invoke("migration_complete",{runId:id});Graphite.events?.emit("migration:completed",{status:done,report,backup:b});return{status:done,report,backup:b};}catch(e){if(begun){try{await Graphite.native.invoke("migration_fail",{runId:id,error:String(e?.message||e)});}catch(_){}}Graphite.events?.emit("migration:error",{error:e});throw e;}finally{running=false;}}
 Graphite.migration={status,run,rollbackToCompatibilitySnapshot,isRunning:()=>running,SOURCE_VERSION};
})();
