use super::sync::{apply_payload, DualWritePayload, SyncReport};
use crate::database;
use rusqlite::{params, Connection, OptionalExtension};
use serde::{Deserialize, Serialize};
use tauri::AppHandle;

#[derive(Debug, Serialize, Clone)]
#[serde(rename_all = "camelCase")]
pub struct MigrationStatus { pub state:String, pub run_id:Option<String>, pub source_version:Option<i64>, pub started_at:Option<i64>, pub completed_at:Option<i64>, pub backup_path:Option<String>, pub last_error:Option<String>, pub updated_at:i64, pub source_of_truth:String }
#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MigrationBeginInput { pub run_id:String, pub source_version:i64, pub backup_path:String }
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct MigrationVerifyReport { pub verified:bool, pub counts:SyncReport, pub expected:SyncReport, pub mismatches:Vec<String> }
fn now_ms()->i64{use std::time::{SystemTime,UNIX_EPOCH};SystemTime::now().duration_since(UNIX_EPOCH).map(|d|d.as_millis() as i64).unwrap_or(0)}
fn row(conn:&Connection)->Result<Option<MigrationStatus>,String>{conn.query_row("SELECT state,run_id,source_version,started_at,completed_at,backup_path,last_error,updated_at FROM migration_state WHERE id=1",[],|r|Ok(MigrationStatus{state:r.get(0)?,run_id:r.get(1)?,source_version:r.get(2)?,started_at:r.get(3)?,completed_at:r.get(4)?,backup_path:r.get(5)?,last_error:r.get(6)?,updated_at:r.get(7)?,source_of_truth:"indexeddb".into()})).optional().map_err(|e|format!("Could not read migration status: {e}"))}
pub fn status(app:&AppHandle)->Result<MigrationStatus,String>{let (conn,_)=database::open(app)?;let mut status=row(&conn)?.unwrap_or(MigrationStatus{state:"idle".into(),run_id:None,source_version:None,started_at:None,completed_at:None,backup_path:None,last_error:None,updated_at:now_ms(),source_of_truth:"indexeddb".into()});status.source_of_truth=if status.state=="completed" { "sqlite".into() } else { "indexeddb".into() };Ok(status)}
pub fn begin(app:&AppHandle,input:MigrationBeginInput)->Result<MigrationStatus,String>{if input.run_id.trim().is_empty(){return Err("Migration run id must not be empty".into())}if input.backup_path.trim().is_empty(){return Err("Migration backup path must not be empty".into())}let(conn,_)=database::open(app)?;let now=now_ms();conn.execute("INSERT INTO migration_state(id,state,run_id,source_version,started_at,completed_at,backup_path,last_error,updated_at) VALUES(1,'running',?1,?2,?3,NULL,?4,NULL,?3) ON CONFLICT(id) DO UPDATE SET state='running',run_id=excluded.run_id,source_version=excluded.source_version,started_at=excluded.started_at,completed_at=NULL,backup_path=excluded.backup_path,last_error=NULL,updated_at=excluded.updated_at",params![input.run_id,input.source_version,now,input.backup_path]).map_err(|e|format!("Could not begin migration: {e}"))?;row(&conn)?.ok_or_else(||"Migration status disappeared after begin".into())}
fn expected_ids(p:&DualWritePayload,key:&str)->Vec<String>{let mut v=match key{"workspaces"=>p.workspaces.iter().map(|x|x.id.clone()).collect(),"notes"=>p.notes.iter().map(|x|x.id.clone()).collect(),"tasks"=>p.tasks.iter().map(|x|x.id.clone()).collect(),"calendar_events"=>p.calendar_events.iter().map(|x|x.id.clone()).collect(),"flashcards"=>p.flashcards.iter().map(|x|x.id.clone()).collect(),"focus_sessions"=>p.sessions.iter().map(|x|x.id.clone()).collect(),_=>Vec::new()};v.sort();v}
fn count(conn:&Connection,table:&str)->Result<usize,String>{conn.query_row(&format!("SELECT COUNT(*) FROM {table}"),[],|r|r.get::<_,i64>(0)).map(|v|v.max(0)as usize).map_err(|e|format!("Could not count {table}: {e}"))}
pub fn import_and_verify(app:&AppHandle,payload:DualWritePayload)->Result<MigrationVerifyReport,String>{let(conn,_)=database::open(app)?;let tx=conn.unchecked_transaction().map_err(|e|format!("Could not start migration transaction: {e}"))?;let expected=apply_payload(&tx,&payload)?;let mut mismatches=Vec::new();let tables=["workspaces","notes","tasks","calendar_events","flashcards","focus_sessions"];for table in tables{let actual=tx.query_row(&format!("SELECT COUNT(*) FROM {table}"),[],|r|r.get::<_,i64>(0)).map_err(|e|format!("Could not count {table}: {e}"))? as usize;let wanted=match table{"workspaces"=>expected.workspaces,"notes"=>expected.notes,"tasks"=>expected.tasks,"calendar_events"=>expected.calendar_events,"flashcards"=>expected.flashcards,"focus_sessions"=>expected.sessions,_=>0};if actual!=wanted{mismatches.push(format!("{table}: expected {wanted}, got {actual}"));}let mut st=tx.prepare(&format!("SELECT id FROM {table} ORDER BY id")).map_err(|e|format!("Could not prepare {table} verification: {e}"))?;let rows=st.query_map([],|r|r.get::<_,String>(0)).map_err(|e|format!("Could not query {table} verification: {e}"))?;let actual_ids=rows.collect::<Result<Vec<_>,_>>().map_err(|e|format!("Could not read {table} verification: {e}"))?;if actual_ids!=expected_ids(&payload,table){mismatches.push(format!("{table}: deterministic id set mismatch"));}}if !mismatches.is_empty(){return Err(format!("Migration verification failed: {}",mismatches.join("; ")))}tx.commit().map_err(|e|format!("Could not commit verified migration: {e}"))?;let counts=SyncReport{workspaces:count(&conn,"workspaces")?,notes:count(&conn,"notes")?,tasks:count(&conn,"tasks")?,calendar_events:count(&conn,"calendar_events")?,flashcards:count(&conn,"flashcards")?,sessions:count(&conn,"focus_sessions")?};Ok(MigrationVerifyReport{verified:true,counts,expected,mismatches})}
pub fn complete(app:&AppHandle,run_id:&str)->Result<MigrationStatus,String>{let(conn,_)=database::open(app)?;let now=now_ms();let changed=conn.execute("UPDATE migration_state SET state='completed',completed_at=?1,last_error=NULL,updated_at=?1 WHERE id=1 AND run_id=?2",params![now,run_id]).map_err(|e|format!("Could not complete migration: {e}"))?;if changed==0{return Err("Migration run is not active or run id does not match".into())}row(&conn)?.map(|mut s| { s.source_of_truth="sqlite".into(); s }).ok_or_else(||"Migration status disappeared after completion".into())}
pub fn fail(app:&AppHandle,run_id:&str,error:&str)->Result<MigrationStatus,String>{let(conn,_)=database::open(app)?;let now=now_ms();conn.execute("UPDATE migration_state SET state='failed',last_error=?1,updated_at=?2 WHERE id=1 AND run_id=?3",params![error,now,run_id]).map_err(|e|format!("Could not record migration failure: {e}"))?;row(&conn)?.ok_or_else(||"Migration status disappeared after failure".into())}
